name: Check my code quality
on:
  push:
    #paths:
      #- currency_convertor/** #doar in interiroul proiectului ruleaza

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout la cod
      - uses: subosito/flutter-action@v2 # install pt flutter
        with:
          channel: 'stable'
      - name: Run format
        run: flutter format -l 120 --set-exit-if-changed .
      - name: Run analysis
        run: flutter analyze